
image: denoland/deno:latest
stages:
  - test
  - deploy

test:
  stage: test
  script:
    - deno fmt --check
    - deno lint
    - deno test -N

deploy:
  stage: deploy
  script:
    - deno install -A jsr:@deno/deployctl --global
    - deployctl deploy
